language: python

cache: pip

install:
  - pip install -r requirements.txt

script:
  - mkdocs build
  - cp CNAME site/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site/
  on:
    branch: master
