language: python

python:
  - "3.5"

cache: pip

git:
  depth: 3

install:
  - pip install -r requirements-python3.txt

script:
  - mkdocs build
  - cp CNAME site/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site/
  on:
    branch: master
