site_name: Makerfactory Documentation
copyright: "&copy; Makerfactory 2018"

extra:
  social:
    - type: globe
      link: https://makerfactory.io
    - type: github
      link: https://github.com/makerfactoryio/docs

theme:
  name: material
  custom_dir: theme
  logo: images/logo.png
  font: false
  include_search_page: false
  search_index_only: true

extra_css:
  - assets/css/font.css
  - assets/css/links.css
  - assets/css/header.css
  - assets/css/search.css
  - assets/css/sidebars.css
  - assets/css/footer.css
  - assets/css/dropdown.css
  - assets/css/nav.css

extra_javascript:
  - assets/js/header.js

nav:
- 'Quick start': index.md
- Getting Started:
  - 'Installing the IDE': 'install.md'
  - 'Programming the board': 'program.md'
- ESP32:
  - 'Core': 'esp32.md'
  - Components:
    - 'USB Programming': 'foo.md'
    - 'Power Supply': 'foo.md'
    - 'mikro BUS': 'foo.md'
    - 'ESP32 module' : 'foo.md'
    - 'Grove' : 'foo.md'
    - 'Temperature' : 'foo.md'
    - 'RGB LED' : 'rgb-led.md'
    - 'OLED-LCD' : 'foo.md'
    - 'UNIT-Bus' : 'foo.md'
    - 'Potentiometer' : 'foo.md'
    - 'I2C Pull-up' : 'foo.md'
    - 'IMU' : 'foo.md'
    - 'Microphone' : 'foo.md'
    - 'LCD' : 'foo.md'
    - 'Menu' : 'foo.md'
    - 'IO' : 'foo.md'
    - 'RFID' : 'foo.md'
    - 'Motor' : 'foo.md'
    - 'SD Card' : 'foo.md'
    - 'Audio Amplifier' : 'foo.md'
    - 'Camera' : 'foo.md'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
