site_name: Makerfactory Documentation
copyright: "&copy; Makerfactory 2019"

extra:
  social:
    - type: globe
      link: https://makerfactory.io
    - type: github
      link: https://github.com/makerfactoryio/docs

theme:
  name: material
  custom_dir: theme
  logo: images/logo.png
  font: false
  include_search_page: false
  search_index_only: true

extra_css:
  - assets/css/font.css
  - assets/css/links.css
  - assets/css/header.css
  - assets/css/search.css
  - assets/css/sidebars.css
  - assets/css/footer.css
  - assets/css/dropdown.css
  - assets/css/nav.css
  - assets/css/extra.css
  - assets/css/float.css
  - assets/css/layout.css
  - assets/css/images.css

extra_javascript:
  - assets/js/header.js

nav:
- Overview: index.md
- Development:
  - ESP32:
    - Quick start: development-boards/esp32/index.md
    - Getting Started:
      - Installing the IDE: development-boards/esp32/install.md
      - Programming the board: development-boards/esp32/program.md
      - Errata sheet: development-boards/esp32/errata_sheet.md
    - Components:
      - Audio Amplifier: development-boards/esp32/audio.md
      - Camera: development-boards/esp32/camera.md
      - ESP32 module: development-boards/esp32/esp32_module.md
      - GPIO: development-boards/esp32/gpio.md
      - Grove: development-boards/esp32/grove.md
      - Gyro (IMU): development-boards/esp32/gyro.md
      - I2C Pull-up: development-boards/esp32/i2c_pull_up.md
      - Menu: development-boards/esp32/menu.md
      - Microphone: development-boards/esp32/microphone.md
      - mikroBUS: development-boards/esp32/mikro_bus.md
      - Motor: development-boards/esp32/motor.md
      - OLED-LCD: development-boards/esp32/lcd.md
      - Potentiometer: development-boards/esp32/potentiometer.md
      - Power Supply: development-boards/esp32/power-supply.md
      - RFID: development-boards/esp32/rfid.md
      - RGB LED: development-boards/esp32/rgb-led.md
      - SD Card: development-boards/esp32/sd_card.md
      - Temperature: development-boards/esp32/temperature.md
      - TFT: development-boards/esp32/tft.md
      - Unit-Bus: development-boards/esp32/unit-bus.md
      - USB Programming: development-boards/esp32/usb-programming.md
      - Webserver: development-boards/esp32/webserver.md
  - M5STACK:
    - Products:
      - Overview: 'm5stack/overview.md'
      - M5STACK Core:
        - M5Core BASIC: 'm5stack/core/black.md'
        - M5Core GRAY: 'm5stack/core/gray.md'
        - M5Core FIRE: 'm5stack/core/fire.md'
        - Quickstart:
          - Overview: 'm5stack/core/quickstart/overview.md'
          - Windows: 'm5stack/core/quickstart/windows.md'
          - macOS: 'm5stack/core/quickstart/macos.md'
          - UIFlow: 'm5stack/core/quickstart/uiflow.md'
          - M5Cloud: 'm5stack/core/quickstart/m5cloud.md'
      - M5STACK Kit:
        - M5GO Kit: 'm5stack/kit/m5go.md'
        - FACES Kit: 'm5stack/kit/faces.md'
        - PROTO Kit: 'm5stack/kit/proto.md'
        - WRISTBAND Kit: 'm5stack/kit/wristband.md'
        - Quickstart:
          - FACES NES Game: 'm5stack/kit/quickstart/faces-nes.md'
      - M5STACK Module:
        - GPS: 'm5stack/module/gps.md'
        - BATTERY: 'm5stack/module/battery.md'
        - PROTO: 'm5stack/module/proto.md'
      - M5STACK Unit:
        - M5Camera: 'm5stack/unit/m5camera.md'
        - Quickstart: 'm5stack/unit/quickstart.md'
      - M5STACK Base:
        - FACES Base: 'm5stack/base/faces.md'
        - Frame Base: 'm5stack/base/frame.md'
        - Loading Base: 'm5stack/base/btc.md'
        - M5GO Base: 'm5stack/base/m5go.md'
        - M5GO Charger: 'm5stack/base/m5go_charger.md'
    - Arduino API:
      - Overview: 'm5stack/api/overview.md'
      - Button: 'm5stack/api/button.md'
      - LCD: 'm5stack/api/lcd.md'
      - MPU9250: 'm5stack/api/mpu9250.md'
      - Power: 'm5stack/api/power.md'
      - Speaker: 'm5stack/api/speaker.md'
      - System: 'm5stack/api/system.md'
      - TF: 'm5stack/api/tf.md'
    - Use-Cases: 'm5stack/cases.md'
    - Related Documents:
      - Overview: 'm5stack/related-documents/overview.md'
      - Establish Serial Connection: 'm5stack/related-documents/serial-connection.md'
      - How to Install Git and Arduino: 'm5stack/related-documents/git-arduino.md'
      - Upgrade M5Stack Lib: 'm5stack/related-documents/upgrade-lib.md'
      - How to Burn Firmware: 'm5stack/related-documents/burn-firmware.md'
      - How to Connect WiFi Using Core: 'm5stack/related-documents/wifi-core.md'
      - How to Connect WiFi Using M5Cloud: 'm5stack/related-documents/wifi-m5cloud.md'
  # - SensorIO:
  #   - Introduction: 'development-boards/sensorio/index.md'
  #   - Getting Started:
  #     - Tooling setup: 'development-boards/sensorio/tools.md'
  #     - Code setup: 'development-boards/sensorio/code-setup.md'
  #     - Compilation: 'development-boards/sensorio/compilation.md'
  #     - Flashing: 'development-boards/sensorio/flashing.md'
  #     - Debugging: 'development-boards/sensorio/debugging.md'
  #     - Demo App: 'development-boards/sensorio/demo-app.md'
  #   - Hardware:
  #     - Overview: 'development-boards/sensorio/hardware-overview.md'
  #     - Circuit Schematics: 'development-boards/sensorio/schematics.md'
  #     - Pinout diagrams: 'development-boards/sensorio/pinouts.md'
  #     - Onboard sensors: 'development-boards/sensorio/sensors.md'
  #     - Expansion Interfaces: 'development-boards/sensorio/interfaces.md'
  #     - Technical specifications: 'development-boards/sensorio/datasheet.md'
  #   - Firmware:
  #     - Overview: 'development-boards/sensorio/fw-overview.md'
  #     - Sensors:
  #       - Light sensor: 'development-boards/sensorio/ltr303.md'
  #       - Accelerometer: 'development-boards/sensorio/bma253.md'
  #     - Peripherals:
  #       - Display: 'development-boards/sensorio/oled.md'
  #       - Relays: 'development-boards/sensorio/relays.md'
  #       - RGB Led: 'development-boards/sensorio/rgbled.md'
  #       - User button: 'development-boards/sensorio/button.md'
  #       - Multiplexers: 'development-boards/sensorio/multiplexers.md'

- Educational Robotics:
  - Hexapod Robobug Platform:
    - Manual:
      - Introduction: 'educational-robotics/robobug-hexapod/introduction.md'
      - Explanation of symbols: 'educational-robotics/robobug-hexapod/explanation_of_symbols.md'
      - Intended Use: 'educational-robotics/robobug-hexapod/intended_use.md'
      - Construction Video: 'educational-robotics/robobug-hexapod/construction_video.md'
      - Package Contents: 'educational-robotics/robobug-hexapod/package_contents.md'
      - Quick start: 'educational-robotics/robobug-hexapod/quick-start.md'
      - Safety Instructions: 'educational-robotics/robobug-hexapod/safety_instructions.md'
      - Required accessories: 'educational-robotics/robobug-hexapod/required_accessories.md'
      - General notes: 'educational-robotics/robobug-hexapod/general_notes.md'
      - Preparatory work: 'educational-robotics/robobug-hexapod/preparatory-work.md'
      - Test firmware installation: 'educational-robotics/robobug-hexapod/test-firmware-installation.md'
      - Preparing the leg servos: 'educational-robotics/robobug-hexapod/preparing-the-leg-servos.md'
      - Assembling the mechanical parts: 'educational-robotics/robobug-hexapod/assembling-the-mechanical-parts.md'
      - Transferring the firmware: 'educational-robotics/robobug-hexapod/transferring-the-firmware.md'
      - Controlling with the Gamepad: 'educational-robotics/robobug-hexapod/controlling-with-the-gamepad.md'
      - Calibrate legs: 'educational-robotics/robobug-hexapod/calibrate-legs.md'
      - Using user boards: 'educational-robotics/robobug-hexapod/using_user_boards.md'
      - Demo programs: 'educational-robotics/robobug-hexapod/demo_programs.md'
      - Overview of the connections and components: 'educational-robotics/robobug-hexapod/Overview_of_the_connections_and_components.md'
      - Schematic system overview: 'educational-robotics/robobug-hexapod/schematic_system_overview.md'
      - Pan & Tilt Unit: 'educational-robotics/robobug-hexapod/pan_tilt_unit.md'
      - Pin assignment of the user board: 'educational-robotics/robobug-hexapod/pin_assignment_of_the_user_board.md'
      - FAQ: 'educational-robotics/robobug-hexapod/FAQ.md'
      - Cleaning: 'educational-robotics/robobug-hexapod/cleaning.md'
      - Declaration of Conformity (DOC): 'educational-robotics/robobug-hexapod/declaration_of_conformity.md'
      - Technical Data: 'educational-robotics/robobug-hexapod/technical_data.md'
    - Example projects:
      - Avoid obstacles with an ultrasonic sensor: 'educational-robotics/robobug-hexapod/project_us_demo.md'
      - Follow objects with an ultrasonic sensor: 'educational-robotics/robobug-hexapod/project_us_follow.md'

- Kits:
  - Tec-Egg:
    - Overview: tec-egg/overview.md
    - Raspberry Pi: tec-egg/raspberry_pi.md
    - Solar: tec-egg/solar.md
    - Ultrasonic: tec-egg/ultrasonic.md
    - Examples:
      - Raspberry Pi: tec-egg/examples.md
 
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.extra
  - markdown_include.include:
      base_path: docs
