site_name: Makerfactory Documentation
copyright: "&copy; Makerfactory 2018"

extra:
  social:
    - type: globe
      link: https://makerfactory.io
    - type: github
      link: https://github.com/makerfactoryio/docs

theme:
  name: material
  custom_dir: theme
  logo: images/logo.png
  font: false
  include_search_page: false
  search_index_only: true

extra_css:
  - assets/css/font.css
  - assets/css/links.css
  - assets/css/header.css
  - assets/css/search.css
  - assets/css/sidebars.css
  - assets/css/footer.css
  - assets/css/dropdown.css
  - assets/css/nav.css

extra_javascript:
  - assets/js/header.js

nav:
- Overview: index.md
- Development Boards:
  - ESP32:
    - Quick start: development-boards/esp32/index.md
    - Getting Started:
      - Installing the IDE: development-boards/esp32/install.md
      - Programming the board: development-boards/esp32/program.md
    - Core: development-boards/esp32/esp32.md
    - Components:
      - USB Programming: development-boards/esp32/foo.md
      - Power Supply: development-boards/esp32/foo.md
      - mikro BUS: development-boards/esp32/foo.md
      - ESP32 module: development-boards/esp32/foo.md
      - Grove: development-boards/esp32/foo.md
      - Temperature: development-boards/esp32/foo.md
      - RGB LED: development-boards/esp32/rgb-led.md
      - OLED-LCD: development-boards/esp32/foo.md
      - UNIT-Bus: development-boards/esp32/foo.md
      - Potentiometer: development-boards/esp32/foo.md
      - I2C Pull-up: development-boards/esp32/foo.md
      - IMU: development-boards/esp32/foo.md
      - Microphone: development-boards/esp32/foo.md
      - LCD: development-boards/esp32/foo.md
      - Menu: development-boards/esp32/foo.md
      - IO: development-boards/esp32/foo.md
      - RFID: development-boards/esp32/foo.md
      - Motor: development-boards/esp32/foo.md
      - SD Card: development-boards/esp32/foo.md
      - Audio Amplifier: development-boards/esp32/foo.md
      - Camera: development-boards/esp32/foo.md
  - SensorIO:
    - Introduction: 'development-boards/sensorio/index.md'
    - Hardware:
      - Overview: 'development-boards/sensorio/hardware-overview.md'
      - Circuit Schematics: 'development-boards/sensorio/schematics.md'
      - Pinout diagrams: 'development-boards/sensorio/pinouts.md'
      - Onboard sensors: 'development-boards/sensorio/sensors.md'
      - Expansion Interfaces: 'development-boards/sensorio/interfaces.md'
      - Technical specifications: 'development-boards/sensorio/datasheet.md'
    - Getting Started:      
      - Tooling setup: 'development-boards/sensorio/getting-started.md'
      - Obtaining code: 'development-boards/sensorio/getting-started.md'
      - Demo App: 'development-boards/sensorio/demo-app.md'
    - Tools:  
      - Tools: 'development-boards/sensorio/tools.md' 

- Educational Robotics:
  - RoboBug Hexapod Platform: educational-robotics/robobug-hexapod/index.md

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - markdown_include.include:
      base_path: docs
